package com.bytewatcher.xiangjiang;

import org.junit.*;
import org.json.*;
import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;
import static org.junit.Assert.*;

public class DiaryStoreTest {
    DiaryStore store;
    @Before public void setup()throws Exception{store=new DiaryStore(Files.createTempDirectory("xiangjiang-test-").toFile());}
    JSONObject record(String text)throws Exception{return new JSONObject().put("id",UUID.randomUUID().toString()).put("text",text).put("place","橘子洲").put("occurredAt","2025-03-15T14:30").put("photos",new JSONArray());}
    JSONObject addPhoto(JSONObject r)throws Exception{String id=UUID.randomUUID()+".jpg";DiaryStore.atomic(store.photo(id),new byte[]{(byte)255,(byte)216,(byte)255,(byte)217});r.getJSONArray("photos").put(new JSONObject().put("id",id).put("source","camera"));return r;}
    byte[] backup()throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();store.backup(b);return b.toByteArray();}
    @Test public void savesEditsAndReopens()throws Exception{JSONObject r=record("看江");store.upsert(r);r.put("text","坐着看江");store.upsert(r);DiaryStore again=new DiaryStore(store.root);assertEquals(1,again.snapshot().getJSONArray("records").length());assertEquals("坐着看江",again.snapshot().getJSONArray("records").getJSONObject(0).getString("text"));}
    @Test public void draftSurvivesProcessRestart()throws Exception{JSONObject r=addPhoto(record("草稿"));store.draft(r);assertEquals(r.toString(),new DiaryStore(store.root).draft().toString());store.clearDraft();assertNull(store.draft());}
    @Test public void invalidDateDoesNotOverwrite()throws Exception{store.upsert(record("已存"));JSONObject bad=record("坏时间").put("occurredAt","tomorrow");assertThrows(Exception.class,()->store.upsert(bad));assertEquals(1,new DiaryStore(store.root).snapshot().getJSONArray("records").length());}
    @Test public void rejectsTraversalAndMissingPhoto()throws Exception{assertThrows(IOException.class,()->store.photo("../private"));JSONObject r=record("照片");r.getJSONArray("photos").put(new JSONObject().put("id",UUID.randomUUID()+".jpg"));assertThrows(IOException.class,()->store.upsert(r));assertEquals(0,store.snapshot().getJSONArray("records").length());}
    @Test public void deletionNeverRemovesMediaAndClearsCover()throws Exception{JSONObject r=addPhoto(record("删除"));String id=r.getJSONArray("photos").getJSONObject(0).getString("id");store.upsert(r);store.presentation("我的日记",id);store.remove(r.getString("id"));assertTrue(store.photo(id).isFile());assertEquals("",store.snapshot().getString("cover"));}
    @Test public void htmlEscapesTextAndEmbedsPhotosAndOmitsLocation()throws Exception{JSONObject r=addPhoto(record("<script>alert('x')</script>"));r.put("location",new JSONObject().put("latitude",28.1234567).put("longitude",112.9).put("accuracy",5));store.upsert(r);ByteArrayOutputStream out=new ByteArrayOutputStream();store.html(out,false);String html=out.toString("UTF-8");assertTrue(html.contains("&lt;script&gt;"));assertFalse(html.contains("<script>"));assertTrue(html.contains("data:image/jpeg;base64,"));assertFalse(html.contains("28.1234567"));}
    @Test public void zipRoundTripAndDuplicateMergeAreIdempotent()throws Exception{store.upsert(addPhoto(record("备份")));DiaryStore target=new DiaryStore(Files.createTempDirectory("xiangjiang-restore-").toFile());File stage=target.inspectBackup(new ByteArrayInputStream(backup()));assertEquals(1,target.mergeBackup(stage));assertEquals(0,target.mergeBackup(stage));assertEquals(1,new DiaryStore(target.root).snapshot().getJSONArray("records").length());target.discardStage(stage);assertFalse(stage.exists());}
    @Test public void backupNeverOverwritesExistingText()throws Exception{JSONObject r=record("旧版本");store.upsert(r);byte[] data=backup();r.put("text","手机新版本");store.upsert(r);File stage=store.inspectBackup(new ByteArrayInputStream(data));assertEquals(0,store.mergeBackup(stage));assertEquals("手机新版本",store.snapshot().getJSONArray("records").getJSONObject(0).getString("text"));}
    @Test public void maliciousZipPathRejected()throws Exception{ByteArrayOutputStream b=new ByteArrayOutputStream();try(ZipOutputStream z=new ZipOutputStream(b)){z.putNextEntry(new ZipEntry("../outside"));z.write(1);z.closeEntry();}assertThrows(IOException.class,()->store.inspectBackup(new ByteArrayInputStream(b.toByteArray())));assertEquals(0,store.snapshot().getJSONArray("records").length());}
    @Test public void corruptSourceIsPreservedNotSilentlyReset()throws Exception{File f=new File(store.root,"diary.json");DiaryStore.atomic(f,"{broken".getBytes());assertThrows(Exception.class,()->new DiaryStore(store.root));assertEquals("{broken",new String(Files.readAllBytes(f.toPath())));}
    @Test public void invalidLocationRejected()throws Exception{JSONObject r=record("错误定位");r.put("location",new JSONObject().put("latitude",91).put("longitude",112).put("accuracy",5));assertThrows(IOException.class,()->store.upsert(r));}
    @Test public void invalidPhotoDataRejected()throws Exception{JSONObject r=addPhoto(record("坏照片"));String id=r.getJSONArray("photos").getJSONObject(0).getString("id");DiaryStore.atomic(store.photo(id),"not-jpeg".getBytes());assertThrows(IOException.class,()->store.upsert(r));}
    @Test public void cannotCleanUnrelatedDirectory()throws Exception{assertThrows(IOException.class,()->store.discardStage(store.root));assertTrue(store.root.isDirectory());}
    @Test public void cleanupProtectsSavedRecordsAndDraftPhotos()throws Exception{JSONObject saved=addPhoto(record("已保存")),draft=addPhoto(record("草稿")),removed=addPhoto(record("已移除"));store.upsert(saved);store.draft(draft);String unused=removed.getJSONArray("photos").getJSONObject(0).getString("id");assertEquals(1,store.pruneUnused());assertFalse(store.photo(unused).exists());assertTrue(store.photo(saved.getJSONArray("photos").getJSONObject(0).getString("id")).exists());assertTrue(store.photo(draft.getJSONArray("photos").getJSONObject(0).getString("id")).exists());}
    @Test public void aiOriginalAndCandidateSurviveReopenAndBackup()throws Exception{JSONObject r=DiaryPolish.candidate(record("原文"),"候选稿","v","api.example.com",new JSONArray(),false);store.upsert(r);assertEquals("原文",new DiaryStore(store.root).snapshot().getJSONArray("records").getJSONObject(0).getString("text"));File stage=store.inspectBackup(new ByteArrayInputStream(backup()));JSONObject restored=new DiaryStore(stage).snapshot().getJSONArray("records").getJSONObject(0);assertEquals("原文",restored.getJSONObject("ai").getString("originalText"));assertEquals("候选稿",restored.getJSONObject("ai").getString("candidate"));store.discardStage(stage);}
    @Test public void aiFieldsCannotCarryApiKey()throws Exception{JSONObject r=DiaryPolish.candidate(record("原文"),"候选稿","v","api.example.com",new JSONArray(),false);r.getJSONObject("ai").put("apiKey","SYNTHETIC_SECRET");assertThrows(IOException.class,()->store.upsert(r));assertEquals(0,store.snapshot().getJSONArray("records").length());}
    @Test public void adoptedHtmlExportsCurrentTextNotHiddenOriginalOrCandidate()throws Exception{JSONObject r=DiaryPolish.adopt(DiaryPolish.candidate(record("PRIVATE_ORIGINAL"),"当前采用稿","v","api.example.com",new JSONArray(),false),true);store.upsert(r);ByteArrayOutputStream out=new ByteArrayOutputStream();store.html(out,false);assertTrue(out.toString("UTF-8").contains("当前采用稿"));assertFalse(out.toString("UTF-8").contains("PRIVATE_ORIGINAL"));}
    @Test public void metadataIsPreservedButNotAutomaticallyApplied()throws Exception{JSONObject r=addPhoto(record("旧图")),p=r.getJSONArray("photos").getJSONObject(0);p.put("originalTime","2025-03-10T09:00").put("originalLocation",new JSONObject().put("latitude",28.1234567).put("longitude",112.9));store.upsert(r);JSONObject saved=new DiaryStore(store.root).snapshot().getJSONArray("records").getJSONObject(0);assertFalse(saved.has("location"));assertEquals("2025-03-15T14:30",saved.getString("occurredAt"));ByteArrayOutputStream out=new ByteArrayOutputStream();store.html(out,false);assertFalse(out.toString("UTF-8").contains("28.1234567"));p.getJSONObject("originalLocation").put("latitude",99);assertThrows(IOException.class,()->store.upsert(r));}
}
