package com.bytewatcher.xiangjiang;

import org.junit.*;
import org.json.JSONObject;
import static org.junit.Assert.*;

public class ModelSettingsFormTest {
    JSONObject existing()throws Exception{return new JSONObject().put("endpoint","https://api.example.com/v1/chat/completions").put("model","vision-test").put("key","synthetic-old-key");}
    @Test public void newConfigurationIsNormalizedWithoutChangingInput()throws Exception{JSONObject empty=new JSONObject();JSONObject next=ModelSettingsForm.prepare(" https://api.example.com/v1/chat/completions "," vision-test "," synthetic-new-key ",empty);assertEquals("https://api.example.com/v1/chat/completions",next.getString("endpoint"));assertEquals("vision-test",next.getString("model"));assertEquals("synthetic-new-key",next.getString("key"));assertEquals(0,empty.length());}
    @Test public void blankKeyIsRetainedOnlyForSameOrigin()throws Exception{JSONObject before=existing();JSONObject next=ModelSettingsForm.prepare(before.getString("endpoint"),"vision-changed","",before);assertEquals("synthetic-old-key",next.getString("key"));assertEquals("vision-test",before.getString("model"));}
    @Test public void pathChangeOnSameOriginKeepsKey()throws Exception{JSONObject next=ModelSettingsForm.prepare("https://api.example.com/new/v1/chat/completions","vision-test","",existing());assertEquals("synthetic-old-key",next.getString("key"));}
    @Test public void domainAndPortChangesRequireNewKey()throws Exception{for(String address:new String[]{"https://other.example.com/v1/chat/completions","https://api.example.com:8443/v1/chat/completions"}){ModelSettingsForm.Invalid error=assertThrows(ModelSettingsForm.Invalid.class,()->ModelSettingsForm.prepare(address,"vision-test","",existing()));assertEquals("key",error.field);assertFalse(error.getMessage().contains("synthetic-old-key"));}}
    @Test public void userCanChangeServiceWithExplicitNewKey()throws Exception{JSONObject next=ModelSettingsForm.prepare("https://other.example.com/v1/chat/completions","another-vision","synthetic-new-key",existing());assertEquals("synthetic-new-key",next.getString("key"));assertEquals("https://other.example.com/v1/chat/completions",next.getString("endpoint"));}
    @Test public void firstConfigurationRequiresKey()throws Exception{ModelSettingsForm.Invalid error=assertThrows(ModelSettingsForm.Invalid.class,()->ModelSettingsForm.prepare("https://api.example.com/v1/chat/completions","vision-test","",new JSONObject()));assertEquals("key",error.field);}
    @Test public void invalidAddressAndModelGetFieldSpecificErrors()throws Exception{for(String address:new String[]{"","http://api.example.com/v1/chat/completions","https://api.example.com/v1/chat/completions?key=synthetic-key","https://key@api.example.com/v1/chat/completions"}){ModelSettingsForm.Invalid e=assertThrows(ModelSettingsForm.Invalid.class,()->ModelSettingsForm.prepare(address,"vision-test","synthetic-key",new JSONObject()));assertEquals("endpoint",e.field);assertFalse(e.getMessage().contains("synthetic-key"));}for(String model:new String[]{" ","v\nInjected","v".repeat(121)})assertEquals("model",assertThrows(ModelSettingsForm.Invalid.class,()->ModelSettingsForm.prepare("https://api.example.com/v1/chat/completions",model,"synthetic-key",new JSONObject())).field);}
    @Test public void invalidKeyCannotBeSavedOrLeakIntoErrors()throws Exception{for(String key:new String[]{"synthetic\r\nInjected","x".repeat(4097)}){ModelSettingsForm.Invalid e=assertThrows(ModelSettingsForm.Invalid.class,()->ModelSettingsForm.prepare("https://api.example.com/v1/chat/completions","vision-test",key,new JSONObject()));assertEquals("key",e.field);assertFalse(e.getMessage().contains("Injected"));}}
    @Test public void unsavedInputDetectionNeverNeedsKeyReadback()throws Exception{JSONObject saved=existing();assertFalse(ModelSettingsForm.changed(saved.getString("endpoint"),saved.getString("model"),"",saved));assertTrue(ModelSettingsForm.changed("https://other.example.com/v1/chat/completions",saved.getString("model"),"",saved));assertTrue(ModelSettingsForm.changed(saved.getString("endpoint"),"different-model","",saved));assertTrue(ModelSettingsForm.changed(saved.getString("endpoint"),saved.getString("model"),"synthetic-typed-key",saved));}
}
