const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
let checks=0;function test(label,fn){fn();checks++;console.log('PASS '+label);}
const trip=JSON.parse(read('maps/itinerary-data.json')),steps=trip.days.flatMap(d=>d.steps),geo=JSON.parse(read('maps/route-data.json'));
test('synthetic data and stable unique 13 steps',()=>{assert(trip.example);assert.equal(steps.length,13);assert.equal(new Set(steps.map(s=>s.id)).size,13);assert.equal(trip.days[0].theme,'岳麓书院');assert.equal(trip.days[1].theme,'橘子洲');});
test('assets generated exactly from safe source',()=>{assert.deepEqual(JSON.parse(read('android-app/app/src/main/assets/trip.json')),trip);const context={window:{}};vm.runInNewContext(read('mobile-guide/site/trip.js'),context);assert.equal(JSON.stringify(context.window.CS_TRIP),JSON.stringify(trip));});
test('map references resolved',()=>{const areas=new Set(['坡子街·餐饮片区','太平街·可选闲逛','湘江中路·住宿区域']);for(const s of steps){for(const p of s.points)assert(areas.has(p)||geo.points.some(x=>x.name===p),p);for(const r of s.routes)assert(geo.routes.some(f=>f.properties.id===r),r);}});
function walk(p){return fs.readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?(['.git','.gradle','build','verification-local','node_modules'].includes(e.name)?[]:walk(path.join(p,e.name))):[path.join(p,e.name)]);}
const files=walk(root);
test('no private identifiers, credentials, machine paths or forbidden artifacts',()=>{const deny=/华润翡翠城|城华路|634[.]29|G391|G424|2026[-.]10[.-](?:17|18)|10\.17—18|全季|下河街78|112[.]9639188|ji-hotel-xiahe78|\/Users\/kyle|\/private\/tmp|github_pat_[A-Za-z0-9_]{15,}|gh[pousr]_[A-Za-z0-9]{25,}|sk-[A-Za-z0-9_-]{20,}|-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/;
 for(const p of files){if(p===__filename)continue;assert(!/\.(apk|aab|jks|keystore|zip|tar)$/.test(p),path.relative(root,p));if(/\.(png|jpg|jar)$/.test(p))continue;assert(!deny.test(fs.readFileSync(p,'utf8')),path.relative(root,p));}});
test('JavaScript syntax and embedded scripts',()=>{for(const p of files){if(/\.(js|cjs)$/.test(p))new vm.Script(fs.readFileSync(p,'utf8'),{filename:path.relative(root,p)});if(p.endsWith('.html'))for(const m of fs.readFileSync(p,'utf8').matchAll(/<script([^>]*)>([\s\S]*?)<\/script>/g))if(!m[1].includes('application/json'))new vm.Script(m[2],{filename:path.relative(root,p)});}});
test('HTML local links and service worker resources present',()=>{for(const page of ['mobile-guide/site/index.html','mobile-guide/site/trip-card.html','legacy-h5/index.html','android-app/map.html']){for(const m of read(page).matchAll(/(?:src|href)="(\.\/[^"#]+|map-data.js)"/g))assert(fs.existsSync(path.resolve(root,path.dirname(page),m[1])),page+' '+m[1]);}const list=read('mobile-guide/site/sw.js').match(/const ASSETS=(\[[^;]+\])/);assert(list);for(const p of JSON.parse(list[1].replace(/'/g,'"')))assert(fs.existsSync(path.join(root,'mobile-guide/site',p==='./'?'index.html':p)));});
test('photo preserved with attribution',()=>{assert.equal(crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'mobile-guide/site/changsha.jpg'))).digest('hex'),'671f504a122aa6ba8f0ffadc6a51346f19fc67dccf55fb38b0e33bb42894ef7b');assert(read('mobile-guide/site/index.html').includes('CC BY-SA 4.0'));});
test('example app isolated from private app',()=>assert(read('android-app/app/build.gradle').includes("applicationId 'com.bytewatcher.xiangjiang.demo'")));
const core=require('../mobile-guide/site/core.js');
test('selection never completes; luggage precedes return',()=>{let s=core.initial(trip);s=core.select(trip,s,'sun-luggage');assert.equal(s.done.length,0);s=core.complete(trip,s);assert.equal(s.step,'sun-return');assert(s.done.includes('sun-luggage'));});
test('corrupt state rejected and moved step follows its actual day',()=>{const s=core.initial(trip,{day:'sun',step:'sun-academy',done:['fake','sat-lunch'],checks:[-1,99,3]});assert.equal(s.day,'sat');assert.deepEqual(s.done,['sat-lunch']);assert.deepEqual(s.checks,[3]);});
console.log(checks+' public source checks passed. Not a device or rendered-layout test.');
